baseURL = 'https://example.org/'
languageCode = 'it-IT'
title = 'Federico Costanzo - Portfolio'
theme = ['gokarna']

buildDrafts = false
buildExpired = false
enableRobotsTXT = true

[params]
  customHeadHTML = '''
    <link rel="stylesheet" href="css/custom.css">
  '''